#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'

cookbook 'rvm', 
	:git => 'git://github.com/fnichol/chef-rvm.git'

cookbook 'git', 
	:git => 'https://github.com/fnichol/chef-git.git'

#cookbook 'postgresql',
#  :git => 'https://github.com/findsyou/cookbooks',
#  :ref => 'postgresql-improvements'
#cookbook 'mysql'

cookbook 'mpd',
	:git => 'https://github.com/i42n/chef-cookbook-mpd'

cookbook 'icecast2',
	:git => 'https://github.com/i42n/chef-cookbook-icecast2'
