#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'

cookbook 'rvm', 
	:git => 'https://github.com/fnichol/chef-rvm',
	:ref => 'master'

cookbook 'git', 
	:git => 'https://github.com/fnichol/chef-git',
	:ref => 'master'

cookbook 'mpd',
	:git => 'https://github.com/i42n/chef-cookbook-mpd',
	:ref => 'master'

cookbook 'icecast2'

# installs required packages like imagemagick or taglib
cookbook 'reliveradio-plantasy-cookbook',
	:git => 'https://github.com/i42n/reliveradio-plantasy-cookbook',
	:ref => 'master'

cookbook 'build-essential'
# use wrapper cookbook to install nginx and configure passenger server
cookbook 'wrapper-nginx-passenger',
	:git => 'https://github.com/i42n/wrapper-nginx-passenger',
	:ref => 'master'

cookbook 'nodejs'
cookbook 'redisio'
cookbook 'postgresql'
#cookbook 'database'