development:
  adapter: postgresql
  encoding: unicode
  database: development
  port: 5432
  pool: 30
  reconnect: true
  username: postgres
  password: hackme

test:
  adapter: postgresql
  encoding: unicode
  database: test
  port: 5432
  pool: 30
  reconnect: true
  username: postgres
  password: hackme

production:
  adapter: postgresql
  encoding: unicode
  database: production
  port: 5432
  pool: 30
  reconnect: true
  username: postgres
  password: hackme
