require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JinglesController do

  # This should return the minimal set of attributes required to create a valid
  # Jingle. As you add validations to Jingle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JinglesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all jingles as @jingles" do
      jingle = Jingle.create! valid_attributes
      get :index, {}, valid_session
      assigns(:jingles).should eq([jingle])
    end
  end

  describe "GET show" do
    it "assigns the requested jingle as @jingle" do
      jingle = Jingle.create! valid_attributes
      get :show, {:id => jingle.to_param}, valid_session
      assigns(:jingle).should eq(jingle)
    end
  end

  describe "GET new" do
    it "assigns a new jingle as @jingle" do
      get :new, {}, valid_session
      assigns(:jingle).should be_a_new(Jingle)
    end
  end

  describe "GET edit" do
    it "assigns the requested jingle as @jingle" do
      jingle = Jingle.create! valid_attributes
      get :edit, {:id => jingle.to_param}, valid_session
      assigns(:jingle).should eq(jingle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Jingle" do
        expect {
          post :create, {:jingle => valid_attributes}, valid_session
        }.to change(Jingle, :count).by(1)
      end

      it "assigns a newly created jingle as @jingle" do
        post :create, {:jingle => valid_attributes}, valid_session
        assigns(:jingle).should be_a(Jingle)
        assigns(:jingle).should be_persisted
      end

      it "redirects to the created jingle" do
        post :create, {:jingle => valid_attributes}, valid_session
        response.should redirect_to(Jingle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jingle as @jingle" do
        # Trigger the behavior that occurs when invalid params are submitted
        Jingle.any_instance.stub(:save).and_return(false)
        post :create, {:jingle => { "title" => "invalid value" }}, valid_session
        assigns(:jingle).should be_a_new(Jingle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Jingle.any_instance.stub(:save).and_return(false)
        post :create, {:jingle => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jingle" do
        jingle = Jingle.create! valid_attributes
        # Assuming there are no other jingles in the database, this
        # specifies that the Jingle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Jingle.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => jingle.to_param, :jingle => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested jingle as @jingle" do
        jingle = Jingle.create! valid_attributes
        put :update, {:id => jingle.to_param, :jingle => valid_attributes}, valid_session
        assigns(:jingle).should eq(jingle)
      end

      it "redirects to the jingle" do
        jingle = Jingle.create! valid_attributes
        put :update, {:id => jingle.to_param, :jingle => valid_attributes}, valid_session
        response.should redirect_to(jingle)
      end
    end

    describe "with invalid params" do
      it "assigns the jingle as @jingle" do
        jingle = Jingle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Jingle.any_instance.stub(:save).and_return(false)
        put :update, {:id => jingle.to_param, :jingle => { "title" => "invalid value" }}, valid_session
        assigns(:jingle).should eq(jingle)
      end

      it "re-renders the 'edit' template" do
        jingle = Jingle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Jingle.any_instance.stub(:save).and_return(false)
        put :update, {:id => jingle.to_param, :jingle => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jingle" do
      jingle = Jingle.create! valid_attributes
      expect {
        delete :destroy, {:id => jingle.to_param}, valid_session
      }.to change(Jingle, :count).by(-1)
    end

    it "redirects to the jingles list" do
      jingle = Jingle.create! valid_attributes
      delete :destroy, {:id => jingle.to_param}, valid_session
      response.should redirect_to(jingles_url)
    end
  end

end
