require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlaylistEntriesController do

  # This should return the minimal set of attributes required to create a valid
  # PlaylistEntry. As you add validations to PlaylistEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "start_time" => "2014-03-22 10:42:36" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlaylistEntriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all playlist_entries as @playlist_entries" do
      playlist_entry = PlaylistEntry.create! valid_attributes
      get :index, {}, valid_session
      assigns(:playlist_entries).should eq([playlist_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested playlist_entry as @playlist_entry" do
      playlist_entry = PlaylistEntry.create! valid_attributes
      get :show, {:id => playlist_entry.to_param}, valid_session
      assigns(:playlist_entry).should eq(playlist_entry)
    end
  end

  describe "GET new" do
    it "assigns a new playlist_entry as @playlist_entry" do
      get :new, {}, valid_session
      assigns(:playlist_entry).should be_a_new(PlaylistEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested playlist_entry as @playlist_entry" do
      playlist_entry = PlaylistEntry.create! valid_attributes
      get :edit, {:id => playlist_entry.to_param}, valid_session
      assigns(:playlist_entry).should eq(playlist_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlaylistEntry" do
        expect {
          post :create, {:playlist_entry => valid_attributes}, valid_session
        }.to change(PlaylistEntry, :count).by(1)
      end

      it "assigns a newly created playlist_entry as @playlist_entry" do
        post :create, {:playlist_entry => valid_attributes}, valid_session
        assigns(:playlist_entry).should be_a(PlaylistEntry)
        assigns(:playlist_entry).should be_persisted
      end

      it "redirects to the created playlist_entry" do
        post :create, {:playlist_entry => valid_attributes}, valid_session
        response.should redirect_to(PlaylistEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved playlist_entry as @playlist_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlaylistEntry.any_instance.stub(:save).and_return(false)
        post :create, {:playlist_entry => { "start_time" => "invalid value" }}, valid_session
        assigns(:playlist_entry).should be_a_new(PlaylistEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlaylistEntry.any_instance.stub(:save).and_return(false)
        post :create, {:playlist_entry => { "start_time" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested playlist_entry" do
        playlist_entry = PlaylistEntry.create! valid_attributes
        # Assuming there are no other playlist_entries in the database, this
        # specifies that the PlaylistEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PlaylistEntry.any_instance.should_receive(:update).with({ "start_time" => "2014-03-22 10:42:36" })
        put :update, {:id => playlist_entry.to_param, :playlist_entry => { "start_time" => "2014-03-22 10:42:36" }}, valid_session
      end

      it "assigns the requested playlist_entry as @playlist_entry" do
        playlist_entry = PlaylistEntry.create! valid_attributes
        put :update, {:id => playlist_entry.to_param, :playlist_entry => valid_attributes}, valid_session
        assigns(:playlist_entry).should eq(playlist_entry)
      end

      it "redirects to the playlist_entry" do
        playlist_entry = PlaylistEntry.create! valid_attributes
        put :update, {:id => playlist_entry.to_param, :playlist_entry => valid_attributes}, valid_session
        response.should redirect_to(playlist_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the playlist_entry as @playlist_entry" do
        playlist_entry = PlaylistEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlaylistEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => playlist_entry.to_param, :playlist_entry => { "start_time" => "invalid value" }}, valid_session
        assigns(:playlist_entry).should eq(playlist_entry)
      end

      it "re-renders the 'edit' template" do
        playlist_entry = PlaylistEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlaylistEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => playlist_entry.to_param, :playlist_entry => { "start_time" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested playlist_entry" do
      playlist_entry = PlaylistEntry.create! valid_attributes
      expect {
        delete :destroy, {:id => playlist_entry.to_param}, valid_session
      }.to change(PlaylistEntry, :count).by(-1)
    end

    it "redirects to the playlist_entries list" do
      playlist_entry = PlaylistEntry.create! valid_attributes
      delete :destroy, {:id => playlist_entry.to_param}, valid_session
      response.should redirect_to(playlist_entries_url)
    end
  end

end
