# This is an example. Rename this template to application.yml and adjust the settings to your needs

# some actions in the app require sending emails to the users
# configure a smtp server here
MAILER_PASSWORD: ppppppppppppppppp
MAILER_FROM_ADDRESS: reliveradio-reminder@i42n.auriga.uberspace.de
MAILER_USERNAME: reliveradio-reminder@i42n.auriga.uberspace.de
MAILER_DOMAIN: i42n.auriga.uberspace.de
MAILER_SERVER_ADDRESS: auriga.uberspace.de

# path to store all the audio files on the server
# this includes podcast episodes and jingles
# make sure this is not inside the capistrano managed folders
# as older releases get deleted after some time
EPISODE_AUDIO_STORAGE_PATH: /home/deploy/audio_storage/